<?php

declare(strict_types=1);

/*
 * Shop categories whose products are not gifts (owner, 2026-09-30: "be very
 * critical about the gifts already in the catalogue ... remove the giftable tag").
 *
 * Judged per category, not per product: 3,647 categories covered 94% of the
 * 320,000 products the gift engine could suggest, and reviewers sorted each into
 * gift, not a gift, or mixed from its name and three sample products. The owner
 * accepted the verdicts as judged. Only "not a gift" is listed; mixed ones stay
 * with the other rules.
 *
 * A product in one of these loses `giftable` and keeps `worth_showing`: no longer
 * suggested as a present, still in search and on pages. A product an editor
 * tagged with an interest, or judged a gift, keeps its verdict
 * (GiftabilityClassifier::classify). Names are the feeds' own, matched without
 * regard to case. Ordered by how many products each held that day, biggest first.
 * To give a category back, take its line out. See docs/features/giftability.md.
 */

return [
    'Téléphonie, mobilité',
    'Voerbak',
    'Kabel',
    'Informatique, réseaux',
    'Étui pour téléphone portable',
    'Câble',
    'Beveiligingscamera',
    'Computer Components & Parts',
    'Campingkooktoestel',
    'Dashcam',
    'Voerautomaat',
    'Monitor',
    'Cameratas',
    'Laptoptas',
    'Koelbox',
    'Oplader',
    'Powerbank',
    'Cartouche d \'encre',
    'Ordinateur: composants, pièces',
    'Bluetooth ontvanger',
    'Solid State Drive (intern)',
    'Sac pour ordinateur portable',
    'Lenses & Filters',
    'Vershouddoos',
    'Écran d\'ordinateur',
    'Externe harde schijf',
    'Caméra de sécurité',
    'DECT-telefoon',
    'Camerafilter',
    'Hub',
    'Nettoyage, repassage',
    'Geheugenkaart',
    'Stofzuiger',
    'Tekenetui',
    'Pro Audio Equipment',
    'Autoradio',
    'Sangle portable',
    'Pro-Audio Equipment',
    'Tracker',
    'Sac pour appareil photo',
    'Camerastatief',
    'Telefoniehouder',
    'Koeler',
    'Hard Drives (HDD, SSD & NAS)',
    'Chargeur',
    'Protecteur d\'écran de téléphonie',
    'Staubsauger & Zubehör',
    'Accessoire pour liseuse électronique',
    'Kachel',
    'TV- & Heim-Audio-Zubehör',
    'Housse pour tablette',
    'Scheermesjes',
    'Usb-stick',
    'Objektive & Filter',
    'Interne voeding',
    'Support mural de télévision',
    'Coque smartphone Apple',
    'Ironing & Vacuuming',
    'Prullenbak',
    'Kattenbak',
    'Ventilator',
    'Stekker',
    'Bureaustoel',
    'Personenweegschaal',
    'RAM-geheugen',
    'Pièce d\'aspirateur',
    'Babyfoon',
    'Stofzuiger onderdeel',
    'Draadloze audio streamer',
    'Überwachungstechnik',
    'Batterie externe',
    'Garten & Terrasse',
    'Monitorbeugel',
    'Pile',
    'Appareils électriques',
    'Trépied d\'appareil photo',
    'Carte mémoire',
    'Koptelefoon oorkussens',
    'Major Appliances Parts & Accessories',
    'Bureau',
    'Office Equipment',
    'Deurbelset',
    'Solid State Drive (extern)',
    'Accessoires hotte',
    'Stiratura e aspirazione',
    'Refroidissement pour ordinateur',
    'Coques Samsung',
    'Opberger',
    'CarConnect',
    'Accessoires image, son',
    'Autospeaker',
    'Oordoppen',
    'Disque dur externe',
    'Batterij',
    'Objectifs, filtres',
    'Stift',
    'Componenti e parti',
    'Steelstofzuiger',
    'Filtre pour hotte aspirante',
    'Kunstkerstboom',
    'Disques durs (HDD, SSD, NAS)',
    'Sportsokken',
    'Poubelle',
    'Fietstas',
    'Box réfrigérant',
    'Boîte alimentaire',
    'Digitale keukenweegschaal',
    'Kruiden & Specerijen',
    'Schakelaar',
    'Lensdop',
    'Équipements professionnels',
    'Luchtontvochtiger',
    'Obiettivi e filtri',
    'Étui à dessin',
    'Element voor Platenspeler',
    'Keukenmachine-accessoire',
    'Tongs',
    'Accessoire pour robot de cuisine',
    'Composants: TV, son',
    'Kast',
    'Kledingstomer',
    'Navigatie',
    'Tripods & Supports',
    'Brandmelder',
    'Luchtbevochtiger',
    'Mengpaneel',
    'Lichtbron',
    'Porte-téléphone',
    'Baby Safety & Health',
    'Dienblad',
    'Droneaccessoire',
    'Clé Usb',
    'Dash Cams, Alarms & Security',
    'Monitors, Projectors & Accs',
    'Afstandsbediening',
    'Supplement',
    'Casa, arredamento e bricolage',
    'Dierenborstel',
    'Mount voor action cam',
    'Tablet & eBook Reader Accs',
    'Weerstandsband',
    'Audio Interface',
    'Campingstoel',
    'Drinkbak',
    'Foamroller',
    'Slimme Verlichting - Accessoire',
    'Filtre de caméra',
    'Kettlebell',
    'Laptop-dockingstation',
    'Auto, moto - pièces, accessoires',
    'Papier',
    'Yogamat',
    'Accessoire aspirateur de table / aspirateur d \'appoint',
    'Elektrowerkzeuge',
    'Monitorstandaard',
    'Muismat',
    'Portables: pièces de rechange',
    'Snoeischaar',
    'E-readeraccessoire',
    'Station d\'accueil pour ordinateur portable',
    'Reisstekker',
    'Router',
    'Balance de cuisine électrique',
    'Garden & Patio',
    'Single board computer',
    'Source lumineuse',
    'Vloerreiniger-apparaat',
    'Cookers, Ovens & Hobs',
    'Hamer',
    'Rolgordijn',
    'Tige',
    'Tuinslang',
    'Câbles, connecteurs',
    'Multifunctionele printer',
    'Brûleur de camping',
    'Cameralens',
    'Hondentuigje',
    'Pc-behuizing',
    'Printer',
    'Traceur GPS',
    'Housse de console',
    'Onderbroek',
    'Ultrasoonreiniger',
    'Bloempot',
    'Shampoo',
    'Accuboormachine',
    'Camerariem',
    'Fietscomputer',
    'PCI uitbreidingskaart',
    'Pèse-personnes',
    'Koffiemachineonderdelen',
    'Support pour came d\'action',
    'Crayon',
    'Elektrisch deurslot',
    'Placard',
    'Notitieboek',
    'Office Supplies',
    'Accu voor digitale camera',
    'Autotoebehoren',
    'Health Care',
    'Rekenmachine',
    'Schroefmachine',
    'Drinkfontein',
    'Jardin, terrasse',
    'Multitool',
    'Trilplaat',
    'Desktopprocessor',
    'Adaptateur secteur',
    'Rasp',
    'Élément pour tourne-disques',
    'Barbecuehoes',
    'Cuillère',
    'DJ Koffer',
    'Macchine da caffè e tè',
    'Papiervernietiger',
    'Sac d\'aspirateur',
    'Sapin de Noël artificiel',
    'Stoomgenerator',
    'Zaad',
    'Keuken garde',
    'Opbouwspot',
    'Inbouwspot',
    'Koeltas',
    'Plafonnière',
    'TV & Home Audio Accessories',
    'Autoentertainment',
    'Tablethoes',
    'Ventilateur',
    'Feestdecoratie',
    'Kniebeschermers',
    'Routeur',
    'Deurmat',
    'Télécommande',
    'Gehoorbeschermer voor kinderen',
    'Computer-Komponenten & -Teile',
    'Kweeklamp',
    'Outils électriques',
    'Ringband',
    'Statief',
    'Support de moniteur',
    'Commutateurs réseau',
    'Druppelsysteem',
    'Gieter',
    'Kweekbak',
    'Vitamins & Lifestyle Supplements',
    'Bladblazer',
    'Deodorant',
    'Chaise de bureau',
    'Accessoire pour cuisinière',
    'Samsung hoesjes',
    'Tuinslanghaspel',
    'Vloerwisser',
    'Opener',
    'Rooster',
    'Treppiedi e supporti',
    'Warmtemeter',
    'Fietsslot',
    'Imprimante',
    'Vitamines et compléments alimentaires',
    'Climatiseurs et radiateurs',
    'Gezichtsreinigingsmiddel',
    'Poepzakjeshouder',
    'Poteau-grattoir',
    'Poêle (chauffage)',
    'Set pour sonnette',
    'Strijkijzer',
    'Coussinets pour casque d\'écoute',
    'Haakse slijper',
    'Heizen, Klima & Sanitär',
    'Housse de table à repasser',
    'Keukenkastorganizer',
    'Sleutelkast',
    'Afstandmeter',
    'Imprimante multifonctionnelle',
    'Intrattenimento in auto',
    'Kabelgoot',
    'Kussenbox',
    'Omvormer',
    'Personal audio - FM-transmitter',
    'Plantenspuit',
    'Printers, Scanners & Supplies',
    'Rasoi manuali e lamette',
    'Regenbroek',
    'Four à micro-ondes',
    'Schoendroger',
    'Bluetoothadapter',
    'Calculatrice',
    'Dishwashing',
    'Disque dur à semi-conducteurs (interne)',
    'Objectiefadapter',
    'Vlekkenreiniger',
    'Boodschappentrolley',
    'Fietsverlichting',
    'Hotte',
    'Koffiefilter',
    'Krabmeubel',
    'Systèmes de contrôle, API',
    'Bac à litière pour chat',
    'Gereedschapsaccu en lader',
    'Ordnung & Aufbewahrung',
    'Stylet',
    'Tuingereedschapset',
    'Waterdichte hoezen',
    'Bagageweger',
    'Bol d\'alimentation',
    'Keukenkraan',
    'Luchtreiniger',
    'Multipurpose Batteries & Power',
    'Netwerkswitch',
    'Spycam',
    'Accessoires robot de cuisine',
    'Applique murale',
    'Cartouche',
    'Compressor',
    'Multiroom Wifi',
    'Thermostats',
    'Trépieds, supports',
    'Vehicle Parts & Accessories',
    'Isolerende flessentas',
    'Labelprinter',
    'Mascara',
    'Vochtmeter',
    'Vrijstaande elektrische kookplaat',
    'Cadenas pour vélo',
    'Decoratieve tak',
    'Kit',
    'Prises de voyage',
    'Snelkoppelingsplaat',
    'Statiefkop',
    'Supports',
    'Chaussettes de sport',
    'Gilet de sécurité',
    'Herbes et épices',
    'Sac réfrigéré',
    'Strijkplank',
    'Apple-smartphonehoesje',
    'Küchenhelfer',
    'Strijkgoedbeschermer',
    'TV-beugel',
    'Accessoires café',
    'Bank',
    'Borstel voor elektrische tandenborstel',
    'Chargeur USB ou chargeur voiture pour smartphone / tablette',
    'Couteau de travail',
    'Lentilles multi-focales',
    'Rangement',
    'Trépied',
    'Besproeiingscomputer',
    'Brosse pour aspirateur',
    'Droogtoren',
    'Eiwitshake',
    'Messgeräte & Tests',
    'Notebookstandaard',
    'Purificateur d\'air',
    'Rangements pour la cuisine',
    'Rolmaat',
    'Schoenenkast',
    'Snijmachine',
    'Beauty & Gesundheit',
    'Bewässerungssysteme',
    'Bosmaaier',
    'Câble USB pour smartphone ou tablette',
    'Dagcrème',
    'Honden droogvoer',
    'Interrupteur',
    'Labelprinterrol',
    'Mémoire vive - RAM',
    'Slips',
    'Switches & Hubs',
    'Voertuigverlichting',
    'Laundry Supplies',
    'Papeterie',
    'Party popper',
    'PLCs & HMIs',
    'Achteruitrijcamera',
    'Ballon',
    'Clavier pour tablette',
    'Dierenkam',
    'Déshumidificateur',
    'Interne harde schijf',
    'Medical & Lab Equipment, Devices',
    'Protecteur d\'écran Smartwatch',
    'Vacuümsealer',
    'Vintage Electronics',
    'Vitamine & Lifestyle Nahrungsergänzungsmittel',
    'Voorraadpot',
    'Vrijstaande magnetron',
    'Wasmachine',
    'Appareils de cuisson',
    'Buitenkabel',
    'Douchemiddel',
    'Illuminazione e studio',
    'Moule à glaçons',
    'Objets publicitaires',
    'Soutien-gorge',
    'Speaker stands',
    'Table',
    'Werkschoenen',
    'Aspirateur',
    'Computer Cables & Connectors',
    'Fietspomp',
    'In-Car Entertainment',
    'Kit de réparation pour téléphone',
    'Vrijstaande oven',
    'Boisson gazeuse',
    'Câble PC / Imprimante',
    'Fil',
    'Handdoekhouder',
    'Harddiskbehuizing',
    'Katten droogvoer',
    'Microgolf',
    'Réparation de peinture pour véhicule',
    'Support audio/vidéo vierge',
    'Batterie pour appareil photo numérique',
    'Boîtier de PC',
    'Fenster, Türen & Treppen',
    'Four à micro-ondes autoportant',
    'Numeriek toetsenbord',
    'Pièces de machine à café',
    'Plafonnier',
    'Presse-purée',
    'Protection d \'écran ou verre trempé pour smartphone',
    'Reliure à anneaux',
    'Sicurezza e antifurti',
    'Cadeaux à distribuer',
    'Mopset',
    'Piles',
    'Regenponcho',
    'Slangkoppeling',
    'Supports d\'enceintes',
    'Vloerreinigingsmiddel',
    'Agent de nettoyage des sols',
    'Haarnet',
    'Lamineermachine',
    'Piles, alimentation',
    'Cat Supplies',
    'Centrale vapeur',
    'GPS & Sat Nav Devices',
    'Raccord de tuyau flexible',
    'Stoomreiniger',
    'Support de tuyau',
    'Ventilators',
    'Washing Machines & Dryers',
    'Étendoir de séchage',
    'Armoire à chaussures',
    'Automat',
    'Couvercle',
    'Kattenbakvulling',
    'Schroevendraaier',
    'Supports et porte-bagages de toit',
    'Tasorganizer',
    'Ventilateurs',
    'Voedingsadapter',
    'Waschmaschinen & Trockner',
    'Aspirateur à manche',
    'Clé USB',
    'Commutateurs, concentrateurs',
    'Fahrradzubehör',
    'Filtre pour aspirateur',
    'Mobiel toilet',
    'Protecteur auditif pour enfants',
    'Table à repasser',
    'Tijdelijke Productclassificatie voor woonproducten',
    'Éclairage faux plafonds',
    'Accessoires pour animal de compagnie',
    'Aspirateurs balai',
    'Clicker',
    'Elektrowerkzeug- & Druckluftgerät-Zubehör',
    'Hydrofiele luier',
    'Laptop Replacement Parts',
    'Power Tool & Air Tool Accessories',
    'Strijkplankhoes',
    'Studio en recording',
    'Étui smartphone Samsung',
    'Accessoires hoverboard/smartscooter',
    'Appareil d\'enregistrement',
    'Couche-culotte',
    'Dischi fissi (HDD, SSD, NAS)',
    'Fontaine à boire',
    'Lepel',
    'Papier imprimante / photo',
    'Perceuse sans fil',
    'Seksspeeltjes reiniger',
    'Steelstofzuigers',
    'Tashengsel',
    'Téléphones fixes',
    'Accessoires machine à laver',
    'Autospiegel',
    'Bloeddrukmeter',
    'Courroie de caméra',
    'Fakkel',
    'Giardino e arredamento esterni',
    'Haushalt',
    'Informatica en netwerken',
    'Maaltijdvervanger',
    'Meststof',
    'Smartwatchbandje',
    'Stylus',
    'Tablettes, liseuses: accessoires',
    'Alarme incendie',
    'Beha',
    'Booster de démarrage',
    'Classification temporaire des produits pour les produits d\'usage général',
    'Gasfles',
    'Keukenreiniger',
    'Kruimelzuiger',
    'Piscine',
    'Putzgeräte',
    'Sac de couchage pour bébé',
    'Sécurité du domicile',
    'Téléphone DECT',
    'Uitzuigpomp',
    'Vaste telefoon',
    'Indoor Air Quality & Fans',
    'Monitor, proiettori, accessori',
    'Multimédia embarqué',
    'Ophanghaak',
    'Protecteur d\'écran de console',
    'Thermostaat',
    'TV-Receiver & Set-Top-Boxen',
    'Automates, moteurs, commandes',
    'Badcape',
    'Bouchons d\'oreilles',
    'Bouton de téléphone',
    'Campingkachel',
    'Cleaning Tools',
    'Elektromaterial',
    'Fahrradteile & -komponenten',
    'Lames de rasoir',
    'Pillendoosje',
    'Sac de rangement',
    'Tandpasta',
    'Visseuse',
    'Accessoires froid',
    'Alimentateur automatique',
    'Bicycle Components & Parts',
    'Brace',
    'Ordinateur d\'arrosage',
    'Partie fer à repasser',
    'Ventilatoren & Luftbehandlung',
    'Aspirateurs avec sac',
    'Bril',
    'Brosse pour brosse à dents électrique',
    'Capuchon d\'objectif',
    'Cleaning kit',
    'Cycling Clothing',
    'Fer à repasser',
    'Gordijn',
    'Hulpmiddel slechthorenden',
    'Motortoebehoren',
    'Rouleau pour impression d\'étiquettes',
    'Steunen',
    'Taille-haie',
    'Telefoonbutton',
    'Werkhandschoenen',
    'Wireless netwerkadapter',
    'Accessoire pour friteuse à air chaud',
    'Auto e moto: ricambi e accessori',
    'Chauffe-biberon et chauffe-aliments pour bébés',
    'Câble / fiche audio',
    'Filtre à eau pour machine à café',
    'Kookwekker',
    'Loopstoel',
    'Lunettes',
    'Onderrok',
    'Support pour moniteur',
    'Sèche-linge à tambour',
    'Veiligheidshesje',
    'Vitamine e integratori',
    'Wasdroger',
    'Allesreiniger',
    'Dispositif de nettoyage pour vitres',
    'Profil',
    'Scooteronderdeel',
    'Supports vierges, accessoires',
    'Thermometer voor lichaam',
    'Zonnebrand',
    'Afficheur pour appareil photo numérique',
    'Babybox',
    'Bureautique',
    'Crèmespoeling',
    'Disque dur interne',
    'Déchiqueteuse',
    'Electrical Supplies',
    'Haarcrème',
    'Heaters & Radiators',
    'Hogedrukreiniger',
    'Lasapparaat',
    'Lenzenvloeistof',
    'Luchtkwaliteitmeter',
    'Pion',
    'Poussette',
    'Ruitenreinigingsapparaat',
    'Siège de bain',
    'Zwemvleugels',
    'Éclairage intelligent - Accessoire',
    'Alarmsysteem',
    'Arroseur de jardin',
    'Carte d\'extension PCI',
    'Creatine',
    'Frisdrank',
    'Housse pour ordinateur portable',
    'Rallonges : accessoires',
    'Raum- & Heizkörperthermostate',
    'Schoonmaakmiddel voor auto',
    'Spot montage en saillie',
    'Stampanti, scanner e forniture',
    'Support pour ordinateur portable',
    'Trépied TV',
    'TV & Video Accessories',
    'Zwembad',
    'Zwembadonderhoud',
    'Arrosoir',
    'Babyfles',
    'Bottes de pluie',
    'Campingtafel',
    'Componenti elettronici',
    'Filter voor afzuigkap',
    'Hand Tools',
    'IJsblokjesvorm',
    'Image, son',
    'Kattenbakfilter',
    'Matras',
    'Nagelknipper',
    'Spatel voor de keuken',
    'Stofzuigers met zak',
    'Waterfles',
    'Wifi multiroom',
    'Accessoire multi-outils',
    'Accessoire pour cuiseur à vapeur ou cuiseur',
    'Accessoire pour mélangeur',
    'Accessoire pour mélangeur à tige',
    'Air & Fuel Delivery',
    'Alimentation interne',
    'Aspirateur traîneau',
    'Brassards de natation',
    'Chaussettes de travail',
    'Cirkelzaag',
    'Compteur de distance',
    'Dunschiller',
    'Extension de portée',
    'Forfait scolaire',
    'Fournitures de bureau',
    'Grip pour le pouce',
    'Heggenschaar',
    'Housse de protection contre la pluie pour caméra',
    'Koel- en vriescombinatie',
    'Netwerkopslag of NAS',
    'Purificateurs d\'eau',
    'Santé et hygiène',
    'Spot encastré',
    'Studio achtergrond doek',
    'Sucettes',
    'Vaste telefoons',
    'Vrijstaande vaatwasser',
    'Werkbroek',
    'Accu',
    'Boorhamer',
    'Brossettes',
    'Colle',
    'Droogrek',
    'Entraîneur de sommeil',
    'Forni e piani cottura',
    'Hamac pour animaux',
    'In-Car Technology, GPS & Security',
    'Instruments de mesure',
    'Litière pour chat',
    'Maaltijdpakketten & -mixen',
    'Orthopedics & Supports',
    'Rasoirs et lames de rasage',
    'Réfrigérateurs, congélateurs',
    'Siège auto',
    'Sportzwembroek',
    'Système de fermeture sous vide',
    'Titulaire de la carte mémoire',
    'Waterzak',
    'Zaklamp',
    'Überwachungstechnik-Teile & -Zubehör',
    'Aspirateurs sans sac',
    'Batterie d\'outils et chargeur',
    'Boîte',
    'Bürotechnik',
    'Campingpan',
    'Compresseur',
    'Computerbril',
    'Entretien de la machine à laver',
    'Festplatten (HDD, SSD & NAS)',
    'Hobbybasisvoorwerp',
    'Hotte aspirante',
    'Matelas',
    'Multitoolaccessoire',
    'Onkruidsteker',
    'Parts & Accessories',
    'Slaapmat',
    'Superfoods',
    'Wasverzachter',
    'Élément de chaise',
    'Accessoires de salle de bain',
    'Accessoires drones',
    'Accessoires smartwatch',
    'Adaptateur réseau sans fil',
    'Appareil de nettoyage de sol',
    'Beveiligingscamera accessoire',
    'Bâton pour s\'asseoir',
    'Carte mère',
    'Carte SD micro-SD ou autre carte mémoire',
    'Commercio, ufficio e industria',
    'Dekbed zonder overtrek',
    'Filtre à café',
    'Gazongereedschapaccessoire',
    'General Household Supplies',
    'Jumpstarter',
    'Laser ontvanger',
    'Measuring & Layout Tools',
    'Navigation',
    'Network accesspoint',
    'Outils électriques et pneumatiques : accessoires',
    'Pièce détachée réfrigérateur',
    'Pulvérisateur de plantes',
    'Sandalen',
    'Sledestofzuiger',
    'Téléphone fixes',
    'Uitlaatriem voor dieren',
    'USB-lader of autolader voor smartphone / tablet',
    'Verlengsnoer',
    'Acc lave-linge / sèchoir / lave-vaisselle',
    'Accessoire voor stomer of koker',
    'Antenne',
    'Boat Parts',
    'Boîtier de disque dur',
    'Computerkoeler accessoire',
    'Désodorisant d\'air',
    'Garagedeuropener',
    'Haarserum',
    'Katten natvoer',
    'Kluis',
    'Outils à main',
    'Ponceuse delta',
    'Smart Watch Accessories',
    'Spelcomputer houder',
    'Telefonie en communicatie',
    'Terrasverwarmer',
    'Toiletreiniger',
    'Transformateur',
    'Attelle',
    'Coffre-fort',
    'Couverture de piscine',
    'Câble vidéo',
    'Déguisements « coloration de cheveux »',
    'Grastrimmer',
    'Haarspray',
    'Harnais pour chien',
    'Hoeslaken',
    'Koffiemachinereiniger',
    'Lave-linges, sèche-linges',
    'Luchtverfrisser',
    'Lutte antiparasitaire',
    'Nappes',
    'Nettoyant pour machine à café',
    'Onkruidbestrijder',
    'Pluggen',
    'Pèse-personne',
    'Schoonmaakdoek',
    'Shampooing pour bébé',
    'Souffleur de jardin',
    'Supports de navigation (voiture)',
    'Visolie',
    'VOIP basisstation',
    'Accessoire de traitement d\'air',
    'Bouteille de gaz',
    'Caleçon de bain sport',
    'Climatizzatori e caloriferi',
    'Fotostudio Set',
    'Handpieces & Instruments',
    'Housse de mobilier de jardin',
    'Partie haut-parleur PA',
    'Personenweegschalen',
    'Pneu pour vélo',
    'Point d\'accès au réseau',
    'Protecteur d\'écran de tablette',
    'Robinet de cuisine',
    'Shampooing',
    'Sicherheitstechnik',
    'Stofzuigers zonder zak',
    'Studioblitze & Zubehör',
    'Tafel',
    'TV, Video & Audio Parts',
    'Vlekkenverwijderaar',
    'Zonnepaneel',
    'Accessoire pour outil à gazon',
    'Accessoires automobiles',
    'Accessoires traitement d \'air',
    'Afvalzak',
    'Balai pulvérisateur',
    'Chemise de sport',
    'Composant lave-vaisselle',
    'Condooms',
    'Doors & Door Hardware',
    'Dweildoek (los)',
    'Entretien de la piscine',
    'Filtre pour le traitement de l\'air',
    'Gobelet',
    'Haartreatment',
    'Home Security',
    'Housse de barbecue',
    'Housse protège-matelas',
    'Imprimante d\'étiquettes',
    'Imprimantes',
    'Kofferhoes',
    'Lighting & Studio',
    'Microfoonstandaard',
    'Pare-soleil d\'objectif',
    'Pré-entraînement',
    'Scanner',
    'TV: récepteurs, décodeurs',
    'Valise DJ',
    'Zwangerschapstest',
    'Accessoires machine à soda ou autre appareil à boissons',
    'Applicateur de matière',
    'Business & Industrial',
    'Campingdouche',
    'Congélateur armoire',
    'Dimmer',
    'Drap-housse',
    'Electronics & Navigation',
    'enrichisseur de café',
    'Feestpakket',
    'Fietsbel',
    'Haarverf',
    'Hottes murales',
    'Nourriture humide pour chats',
    'Pantalon amincissant',
    'Peinture de travaux',
    'Ponceuse orbitale',
    'Potgrond',
    'Scooteraccessoire',
    'Set bistro',
    'Support écran PC',
    'Takkenschaar',
    'Tape',
    'Tenttapijt',
    'Verkleedhaarkleuring',
    'Wifi-antenne',
    'Accessoire pour poussette',
    'Accessoires 3D',
    'Aiguille pour tourne-disques',
    'Bande',
    'Buitenvogelvoer',
    'Camping Stoves, Ovens & BBQs',
    'Cardreader',
    'Cavi e connettori',
    'Chariot de courses',
    'Chauffage de terrasse',
    'Combinaison de pluie',
    'Conserven',
    'Dierentondeuse',
    'Fietsendragers',
    'Fotobehang',
    'Garen',
    'Garnering',
    'Impédancemètre ou pèse-personne électronique ou mécanique balance',
    'Inbouwvaatwasser',
    'IP Camera',
    'Klustang',
    'Limonades',
    'Meuble intégré pour machine à laver le linge',
    'Nettoyant anti-taches',
    'Recordable/Rewritable',
    'Slinger',
    'SSD HDD bracket',
    'Stoelonderdeel',
    'Thee-ei',
    'Tool Boxes & Storage',
    'Tuinsproeier',
    'TV & Home Audio Parts',
    'TV- & Heim-Audio-Teile',
    'Verwarmingsaccessoire',
    'Vloerreinigers',
    'Windbescherming voor Microfoon',
    'Accessoires grille / gaufrier',
    'Accessori utensili pneumatici, elettrici',
    'Alarmes, sécurité, caméras',
    'Auto uitleesapparatuur',
    'Autres accessoires audio',
    'Bistroset',
    'Blenderaccessoire',
    'Bootuitrusting',
    'Bouilloire à eau',
    'Chaise haute',
    'Funsport',
    'Hondensnack',
    'Kas',
    'Kledingontpluizer',
    'Klimageräte & Heizgeräte',
    'Lijm',
    'Matelas gonflable (camping)',
    'Multi-outil',
    'Navigatie (auto) houders',
    'Nettoyeurs de sols',
    'Paravent de jardin',
    'Photo Studio Set',
    'Plantensteun',
    'Poignée de sac',
    'Powerline-adapter',
    'Radiateur design',
    'Range extender',
    'Scheerkop',
    'Schroefmachine accessoire',
    'Sportonderbroek',
    'Statiefvoetje',
    'Tensiomètre',
    'Voeropslag',
    'Watch Accessories',
    'Accessoire appareil à sodas',
    'Accessoire pour hotte aspirante',
    'Accessoires four / four à vapeur',
    'Accessoires voor scheerapparaten',
    'Aspirateur balai',
    'Babyhuidverzorging',
    'Breastfeeding/Nursing',
    'Bricolage',
    'Café, capsules & dosettes',
    'Caméra de surveillance',
    'Charbon de bois',
    'Computer Randapparatuur Accessoires',
    'Dierenmat',
    'Digitale of mechanische personenweegschaal',
    'Drukker',
    'Fietsband',
    'Gif voor ongedierten',
    'Haarolie',
    'Home Appliances',
    'Kit d\'entretien machine à café',
    'Koelelement',
    'Kussensloop',
    'Lave-linge',
    'Luchtbehandelingaccessoire',
    'Motorolie',
    'PA versterker',
    'Panneau solaire',
    'Pare-soleil siège enfant',
    'Plaque de contact du gril',
    'Semelles intérieures',
    'Sportlegging',
    'Stekkerdoos',
    'Teinture pour cheveux',
    'Ufficio e cancelleria',
    'Wasmachine-opbouwmeubel',
    'Aminozuren',
    'Auto-organizer',
    'Automation, Antriebe & Motoren',
    'Autres acc. gros électro',
    'Bakingrediënt',
    'Brosse pour animaux',
    'Chaise à bascule bébé',
    'Chemisier',
    'Chips',
    'Câble audio',
    'Delta-schuurmachine',
    'Draagtas',
    'Drucker, Scanner & Zubehör',
    'Enzymen',
    'Garnir',
    'Gilet réfléchissant',
    'Handdoek voor dieren',
    'Haushaltsbatterien & Strom',
    'Heizungs- & Klimaanlagen-Teile & -Zubehör',
    'Jauge de chaleur',
    'Ketelstofzuiger',
    'Lijmstift',
    'Lingettes',
    'Maillot de corps',
    'Medical/Lab Equipment Attachments & Accessories',
    'Mineralen',
    'Naald voor platenspeler',
    'Nettoyeur à vapeur',
    'Pack de glace',
    'Pièces, accessoires',
    'Plantenstandaard',
    'Shampooing voitures',
    'Sodamakeraccessoire',
    'Taille crayon',
    'Thermostat',
    'Tochtstrip',
    'Tête de rasage',
    'USB-kabel voor smartphone of tablet',
    'Bandanas',
    'Binnen/Buitenthermometer',
    'Blank Audio/Video Media',
    'Cameracleaning',
    'Caravanhoes',
    'Chargeur ou adaptateur universel pour ordinateur portable',
    'Corps (lingerie)',
    'Coussin de camping',
    'Câble de chargement pour ordinateur de jeu',
    'Embout de tournevis',
    'Enterprise Networking, Servers',
    'Entretien du linge',
    'Ethernet adapter',
    'Filter voor luchtbehandeling',
    'Fraise',
    'Heavy Equipment, Parts & Attachments',
    'Klusverf',
    'Lavatrici e asciugatrici',
    'Ongediertewering',
    'Oplader voor digitale camera',
    'Oreiller',
    'Outillage électrique',
    'Sac à déchets',
    'Schilmes',
    'Support / pied d \'enceinte',
    'Support mural TV',
    'Tafellaken',
    'Verfspuit',
    'Wieg',
    'Écran de projection',
    'Accessoire pour enceinte sans fil',
    'Accessoires appareils de cuisine',
    'Accessoires repassage',
    'Boîte à outils',
    'Brosse en acier',
    'Convectoren',
    'Dierenvoedingssupplement',
    'Décoration de gâteaux',
    'Fers à repasser',
    'Haarmasker',
    'Handzeep',
    'Keukenhaken',
    'Klavier / Toetsenbord',
    'Lampe continu de studio',
    'Lit',
    'Personal Protective Equipment (PPE)',
    'Persoonlijk alarm',
    'Piles & chargeurs',
    'Plantes et sols : soins et accessoires',
    'Printers',
    'Processeur de bureau',
    'Projectiescherm',
    'Prothèse pour les malentendants',
    'Présentateur',
    'Ricambi TV e home audio',
    'Réfrigérateur encastré',
    'Réseau d\'entreprise, serveurs',
    'Scie circulaire',
    'Shipping Labels & Tags',
    'Sistemi di controllo e PLC',
    'Sonnette de vélo',
    'Vacuümzakken',
    'Électricité',
    'Étiquettes et bordereaux',
    'Acc. nettoyeur à vapeur / lave-vitre',
    'Accessoires de vélos',
    'Accessoires friteuse',
    'Accessoires koffiezetter',
    'Accouplement en S pour grue',
    'Blank Media & Accessories',
    'Concealer',
    'Convecteurs',
    'Electrical Tools',
    'Empennage',
    'Envelopes & Mailers',
    'Grasmaaier',
    'Housse pour accessoires de Sports d\'hiver',
    'Inbouwwandlamp',
    'Keukenweegschalen',
    'Ladenkassen & Scanner',
    'Lave-vaisselle autoporteur',
    'Maatbeker',
    'Meubelroller',
    'Modules périphériques API',
    'Natural & Alternative Remedies',
    'Objectieftas',
    'Pinceaux',
    'Pompe à vélo',
    'Routeur wi-fi',
    'RV, Trailer & Camper Parts & Accessories',
    'Sd- micro-sd-kaart of andere geheugenkaart',
    'Steuersysteme & SPS',
    'Strijkijzers',
    'Tafelonderdeel',
    'Ventilatie- en airconditioningaccessoire',
    'Verfroller',
    'Vriezer',
    'Werkmes',
    'Zeef',
    'Zelfbruiner',
    'Zonnekappen',
    'Accessoire voor sigaretten',
    'Adaptateur CPL',
    'Adoucissant',
    'Allaitement',
    'Autolakherstel',
    'Borstkolf',
    'Brilreinigingsmiddel',
    'Chemin de câble',
    'Chemise à élastique',
    'Chiffon de nettoyage',
    'Combisysteem steel',
    'Computer: onderdelen',
    'Couverture de pluie',
    'Degré Arch',
    'Dekbed',
    'Eclairage, studio',
    'Energiegel',
    'Fauteuil',
    'Fichier',
    'Filtre de piscine',
    'Flash Studio',
    'Four encastré',
    'Fridges & Freezers',
    'Generator',
    'Inbouwoven',
    'Lighting & Lamps',
    'Machines à compter l\'argent',
    'Meuleuse d\'angle',
    'Modem',
    'Nettoyeur de sol 2-en-1',
    'Nettoyeur haute pression',
    'Opbergtas',
    'Opzetzonnebril',
    'Outils pour vélo',
    'Poncho de pluie',
    'Porte-serviettes',
    'Portemine',
    'Protecteur d\'écran de navigation',
    'Reflectievest',
    'Savon pour la douche',
    'Schwimmbeckenbedarf',
    'Sportbroek',
    'Supports GSM voiture',
    'Tableau blanc',
    'Tacker',
    'Tasse d\'école',
    'Textielverfrisser',
    'Thermoset',
    'Tijdelijke Productclassificatie voor elektronicaproducten',
    'Torchon et torchon de cuisine',
    'Wastafelkraan',
    'Éclairage de vélo',
    'Élément de banc',
    'Étui pour casque d\'écoute',
    'Accessoires de piscine',
    'Accessoires sodamachine of ander drankapparaat',
    'Afzuigkap',
    'Andere accessoires stofzuiger',
    'Bakbonen',
    'Binnenvogelvoer',
    'Boodschappentas',
    'Catadioptre pour vélo',
    'Centrales vapeur',
    'Chargeur pour appareil photo numérique',
    'Clavier numérique',
    'Combinaison de réfrigération et de congélation',
    'Controller behuizing',
    'Deksel',
    'DJ Turntable Parts & Accessories',
    'Déodorant',
    'EHBO-kit',
    'Farben, Beizen & Lacke',
    'Feuille de transparence',
    'Ladder',
    'Lave-linges frontaux',
    'Lecteur de cartes',
    'Luier',
    'Natur- & Alternativheilmittel',
    'Onderdeel koelkast',
    'Pantalon de pluie',
    'Pre-workout',
    'Regenhoes voor camera',
    'Regolazione luce',
    'Schrijfmap',
    'Semences',
    'Solarenergie',
    'Speakerhoes',
    'Tarp',
    'Tasse à mesurer',
    'Toiletbril',
    'Tubeknijper',
    'Ultrasone verjager',
    'USB memory stick',
    'Vision Care',
    'Vitaminen',
    'Vloerkussen',
    'Wandsteun',
    'Waterpomp',
    'Afslankbroekje',
    'Afzuigkapaccessoire',
    'Appareil photo numérique - kit de démarrage',
    'Autoantenne',
    'Badkamermat',
    'Camera Bracket',
    'Camping-Küchenbedarf',
    'Campingkruk',
    'Collation pour chien',
    'Digitale pen',
    'DJ Tas',
    'Firmennetzwerke & Server',
    'Harde schijf of SSD',
    'Hottes télescopiques',
    'Housse tablette Apple',
    'Inbouw elektrische kookplaat',
    'Keukenspoelbak',
    'Lak',
    'Lave-vaisselles et pièces',
    'Mifi router',
    'Neusinhaler',
    'Objets ménagers',
    'Office-software',
    'Ongedierteval',
    'Planches à repasser',
    'Plaspot',
    'Radiatorknop',
    'Réchauds, fours, grills',
    'Schaduwdoek',
    'Schoolpakket',
    'Schroefbit',
    'Set tafel en stoelen',
    'Software',
    'Spelcomputer laadkabel',
    'Supporti vergini e accessori',
    'Système de repassage',
    'Table de camping',
    'Tuinbank',
    'Tuinhuis',
    'TV-ontvanger',
    'Vloerreiniger 2-in-1',
    'Zwembadreinigingsmiddel',
    'Accessoire pour refroidisseur d\'ordinateur',
    'Accessoires pour moteur',
    'Accessoires voor fitnessapparatuur',
    'Afdruipmat',
    'Airco',
    'Articles d\'entretien',
    'Autres accessoires PC',
    'Autres accessoires photo et vidéo',
    'Autres accessoires tablette',
    'Bathroom Accessories',
    'Bewegingsmelder',
    'Bonnet de bain',
    'Boîte prise de courant',
    'Caleçon de bain',
    'Carkit',
    'Composant de montage radiateur',
    'Coupe-herbe',
    'Détecteur de fumée',
    'Energielamp',
    'Enregistrable/réenregistrable',
    'Ensemble de fête',
    'Etiket',
    'Filtre à eau',
    'Fond d\'écran photo',
    'Foot Controls, Pedals & Pegs',
    'Gants de four',
    'Gaskocher, Backöfen & BBQs',
    'Gereedschapstas',
    'Hobbyschaar',
    'Housse de protection pour trampoline',
    'Hub USB',
    'Jewelry Care, Design & Repair',
    'Keramische radiators',
    'Keukenschaar',
    'Kooi',
    'Kookplaataccessoire',
    'Lijmklem',
    'Lunettes pour ordinateur',
    'Mouvement rotatif, linéaire',
    'Officemes',
    'Padverlichting',
    'PLC Peripheral Modules',
    'Point of Sale (POS) Equipment',
    'Porte-tablette',
    'Prise de courant murale',
    'Projectors & Presentation Equipment',
    'Purificateurs d\'air',
    'Règle',
    'Réfrigérateur',
    'Salute',
    'Smart-Türklingeln & -Türschlösser',
    'Solo microgolfovens',
    'Store à rouleau',
    'Système d \'alarme connecté',
    'Table de cuisson électrique encastrable',
    'Telefoniereparatiekit',
    'Thee- en keukendoek',
    'Tour de séchage',
    'Transformateurs',
    'Turbos, Superchargers & Intercoolers',
    'Tv statief',
    'Téléphone sans fil',
    'Têtes de rasage',
    'Voorraadbus',
    'Accessoire pour machine à coudre',
    'Accessoires de GPS',
    'Batterijoplader',
    'Blaasradiators',
    'Boîte micro-ondes',
    'Boîtier de régulateur',
    'Business, Office & Industrial',
    'Chauffage d \'appoint',
    'Coffret à couverts',
    'Colle loisirs',
    'Cuisinière à gaz',
    'Decoratieve letters en cijfers',
    'Deurbelonderdeel',
    'Drankdispenser',
    'Détachant',
    'Electrical Equipment & Supplies',
    'Embout soie dentaire',
    'Exterior Parts & Accessories',
    'Fietsreflector',
    'Filter adapter',
    'Hakselaar',
    'Huishoudhandschoen',
    'Huistelefoon',
    'Hydraulics, Pneumatics, Pumps & Plumbing',
    'Insectenlamp',
    'Kleefpasta',
    'Kochen & Essen',
    'Laminating Equipment',
    'Light Equipment & Tools',
    'Luchtreinigers',
    'Manomètre de pression des pneus',
    'Micro-ondes solo',
    'Naaimachineaccessoire',
    'Nettoyant de cuisine',
    'Nettoyant pour vitres et pare-brise',
    'Organisateur de sac',
    'Pack de Gel',
    'Pendule',
    'Piège à insectes',
    'Poetsmiddel',
    'Pompe à eau',
    'Potlodendoos',
    'Presentation/AV/Projectors',
    'Presenter',
    'Racks & Roof Boxes',
    'Radiateurs bain d\'huile',
    'Radiateurs soufflants',
    'RC Model Vehicle Parts & Accs',
    'Remorque pour vélo',
    'Ricambi e accessori',
    'Rideau',
    'Rouleau correcteur',
    'Réfrigérateur 1 porte',
    'Seghe a motore',
    'Shake protéiné',
    'Sportdrank',
    'Station de base VOIP',
    'Stillzubehör',
    'Stoomgenerators',
    'Support voiture',
    'Système d\'alarme',
    'Tapis de sol',
    'Tente de fête',
    'Test de grossesse',
    'Thermomètre intérieur/extérieur',
    'Tuyau d\'arrosage',
    'Tête de trépied',
    'Wandcontactdoos',
    'Weckpot',
    'Whiteboard',
    'Zwembroek',
    'Zwemtas',
    'Équip. surveillance et alarme',
    'Acc. appareils audios portables',
    'Accessoire de ventilation et de climatisation',
    'Accessoire pour fer à repasser',
    'Accessoires / sacs sous vide',
    'Aircooler',
    'Arbre de fléchettes',
    'Aspirateur à chaudière',
    'Badkamerrek',
    'Balai à franges',
    'Boiler',
    'Boor',
    'Cadeauverpakking',
    'Congélateurs bahut',
    'CVC: pièces',
    'Deurbel',
    'Douche- en badrekje',
    'Electronic Components & Semiconductors',
    'Fiche bristol',
    'Filtre à eau pour le réfrigérateur',
    'Fours encastrables',
    'Fours pose-libre',
    'Guitar & Bass Parts',
    'Haut-parleur de voiture',
    'Hobbydecoratieobject',
    'Hobbylijm',
    'Kit de nettoyage',
    'Klopboormachine',
    'Kofferonderdelen',
    'Lasdoos',
    'Lave-vaisselle pose-libre',
    'Lens converter',
    'Machine à plastifier',
    'Mallettes de voyage',
    'Meubelmontageonderdeel',
    'Naambadge',
    'Nettoyeurs à vapeur',
    'Noodpictogram',
    'Olieradiators',
    'Opzetkookplaat',
    'Outillage à main',
    'Ovenwanten',
    'Overall',
    'Panier pour bicyclette',
    'Papier, Büro- & Schreibwaren',
    'Plaque pour gaufrier',
    'Portes et quincaillerie',
    'Protection individuelle, ÉPI',
    'Raamfolie',
    'Radiateurs céramiques',
    'Remote shutter release',
    'Replacement Parts & Tools',
    'Réchaud électrique',
    'Réfrigérateurs de table',
    'Sac à provisions',
    'Schroeven',
    'Schwimmbecken, Saunen & Außenwhirlpools',
    'Seats, Parts & Accessories',
    'Slot',
    'Smart alarmsysteem',
    'Sonstige Branchen & Produkte',
    'Stoomreinigers',
    'Stoomstrijkijzer',
    'Strijkijzer accessoire',
    'Support de plafond pour projecteur',
    'Tapis de course',
    'Tapis de cuisson',
    'Taque à induction',
    'Taques au gaz',
    'Taques vitrocéramiques',
    'TV Reception & Set-Top Boxes',
    'Warmhoudketel',
    'Wasmand',
    'Wetsuits & Drysuits',
    'Zwembadstofzuiger',
    '3D-printer filament',
    'Aardlekschakelaar',
    'Accessoire caméra de sécurité',
    'Accessoires soin du corps et du visage',
    'adaptateur Ethernet',
    'amplificateur PA',
    'Antenne Wifi',
    'Apparecchiature professionali e DJ',
    'Articoli per cani',
    'Audio-/Video-Leermedien',
    'Badpak',
    'Batterie',
    'Bench',
    'Bijverwarming',
    'Bol / Boîte de conservation',
    'Boorset',
    'Briquet',
    'Bâton de colle',
    'Capsules / pads',
    'Chaussures de travail',
    'Chemischtoiletvloeistof',
    'Classification temporaire des produits pour les produits électroniques',
    'Composant d\'ordinateur portable',
    'Compressiekousen',
    'Drives & Motor Controls',
    'Désodorisant textile',
    'Fietsbeschermhoes',
    'Fietsjack',
    'Flesvoeding',
    'Fotorolletje',
    'Genouillères',
    'Hogedrukreinigers',
    'Home Audio Accessories',
    'Housse de haut-parleur',
    'Housses étanches',
    'Industrial Automation & Motion Controls',
    'Kitchen',
    'Lichtformer',
    'Licol',
    'Liniaal',
    'Machine à laver',
    'Messwerkzeuge & Messgeräte',
    'Meubelknop',
    'Motorhandschoenen',
    'Multifocale lenzen',
    'Nettoyant tout usage',
    'Nettoyeurs de vitres',
    'Nettoyeurs haute pression',
    'Nourriture sèche pour chats',
    'Nourriture sèche pour chiens',
    'Ontkalkingsmiddel',
    'Outdoorbroek',
    'Panier à linge',
    'PC barebone',
    'Pedalen',
    'Penvulling',
    'Pichet avec filtre à eau',
    'Pièces',
    'Plaques',
    'Porte-pièces de rechange',
    'Regenpak',
    'Relais',
    'Rok',
    'Rookgasafvoermateriaal',
    'Sac DJ',
    'Sac pour disque dur',
    'Sac à outils',
    'Sandales',
    'Sensors',
    'Swimwear',
    'Switches',
    'Termostati',
    'Tire-lait',
    'Tuinkussen',
    'Tuinmeubelhoes',
    'Vacuümbak',
    'Verband',
    'Verlängerungskabel & Zubehör',
    'Vliegenmasker',
    'Vloerwisser accessoires',
    'Werksokken',
    'Wifirouter',
    'Wintersport accessoire cover',
    'Accessoire pour nettoyeur haute pression',
    'Accessoire pour tournevis',
    'Adhesives & Tape',
    'Afslanksupplement',
    'Air Intake & Fuel Delivery',
    'Anorak de ski',
    'Appareil anti-peluches pour vêtements',
    'Appareil d\'électrothérapie à électrodes',
    'Aspirateur de miettes',
    'Aspirateur de table',
    'Aspirateurs de table',
    'Autostoelhoes',
    'Balai',
    'Bestekcassette',
    'Blazer/Colbert',
    'Bloc-notes',
    'Boissons non alcoolisées',
    'Borstkolf onderdeel',
    'Bougiesleutel',
    'Bouwstofzuigers',
    'boîte de câble',
    'Ciseaux de cuisine',
    'Compas',
    'Contrôle des algues',
    'Decoupeerzaag',
    'Drumkoffer',
    'Débroussailleuse',
    'Encre',
    'Erneuerbare Energie',
    'Fers à réservoirs XL',
    'Frigoriferi e congelatori',
    'Gant de ménage',
    'Gasslang',
    'Gelpack',
    'Gereedschapscombiset',
    'GPS e navigatori satellitari',
    'Grooming',
    'Handstofzuigers',
    'Helmets & Accessories',
    'Hottes sous-encastrables',
    'Housse de protection pour vélo',
    'Housse tablette',
    'Inlegzolen',
    'Interface/Add-On Cards',
    'Kit de superposition',
    'Koffiemachineonderhoudset',
    'Lampe insecte',
    'Light Controls & Modifiers',
    'Machines sous vide',
    'Magnetronaccessoire',
    'Matelas supérieur',
    'Matériel de cuisine',
    'Mini vriezer',
    'Modeltreinonderdeel',
    'Motorbroek',
    'Mât de drapeau',
    'Nettoyeurs tapis',
    'Neusdouche',
    'Ontbijtgranen',
    'Organisateur de siège automobile',
    'Outdoorshirt',
    'Papier Loisir',
    'Parrucche ed extension',
    'Parts',
    'Pince de cuisine',
    'Produit de nettoyage pour piscine',
    'Protection d \'écran tablette',
    'Reisbox voor melkpoeder',
    'Roljaloezieën',
    'Ruitenwassers',
    'Réhausseur de chaise',
    'Set pour sceller les vitres lors de l\'utilisation d\'un climatiseur',
    'Sewing Machine Parts & Accs',
    'Sistemi di allarme, sorveglianza',
    'Softbox',
    'Sonnette',
    'Sportsupplement',
    'Starters, Alternators, ECUs & Wiring',
    'Stoelverkleiner',
    'Stores à rouleau',
    'Support de disque dur SSD',
    'Switch e hub',
    'Sägen',
    'Tandenborstelhouder',
    'Tapijtreinigers',
    'Tennisballen',
    'Tensiomètre / Cardiofréquencemètre / Oxymètre de pouls',
    'Tensiomètres',
    'Tentelastiek',
    'Tondeuses pour animaux',
    'Tonneau de pluie',
    'Tournevis',
    'Tuinstrooisel',
    'Tussendoortje',
    'Tuyau de gaz',
    'Vensterzonwering',
    'Veste d\'extérieur',
    'Vloerkleed',
    'Voertuigonderhoudsmiddel',
    'Voile d\'ombrage',
    'Vrijstaande ovens',
    'Wheels, Tires & Parts',
    'Zitverhoger',
    'Électrostimulation',
    'Étagère mural',
    'Étui de protection pour clé de voiture',
    'Accessoire voor frituurpan',
    'Accessoires GPS',
    'Aircoolers',
    'Aspirateur de piscine',
    'Aspirateurs chantier',
    'Audio, Communication & Navigation',
    'Autres accessoires TV',
    'Backöfen & Herde',
    'Badkamerventilator',
    'Behang',
    'Bike Accessories',
    'Bottes de moto',
    'Boîte à coussins',
    'Brassard de sport',
    'Büro-Kommunikation',
    'Campingvoetenbank',
    'Chaise de jardin',
    'Chargeur pour vélo électrique',
    'Ciseaux-sécateur',
    'Climatiseurs mobiles',
    'Clé USB wi-fi / Récepteur Bluetooth',
    'Clôture de sécurité',
    'Congélateurs de table',
    'Couche hydrophile',
    'Câble pour guitare',
    'Desktopstandaard',
    'Dieren anti-vlo en -teekmiddel',
    'Dompelaar',
    'Décoration d\'aquarium',
    'Eetkamerstoel',
    'Eiwitreep of -snack',
    'Elektriciteitsmeter',
    'Elektromotor',
    'Ersatzteile & Zubehör',
    'Essuie-glace de douche',
    'Fiets',
    'Film de plastification',
    'Filtres Fontaine',
    'Final & Primary Drive Parts & Kits',
    'Flash Lighting',
    'Flightcases',
    'Floodlight',
    'Fouet de cuisine',
    'Frietsnijder',
    'Handwerkzeuge',
    'Heetwaterdispenser',
    'Hoortoestel schoonmaakmiddel',
    'Housse pour appareil photo / caméra',
    'Instappers',
    'Kabelklemmen- en houders',
    'Keukenbrander',
    'Knoflookpers',
    'Kruimeldief',
    'Landkaart',
    'Laptoponderdeel',
    'Lecteur optique',
    'Loungewear shirt',
    'Maillot de bain',
    'Measuring Tools',
    'Meubelgreep',
    'Micro-ondes pose-libre avec grill',
    'Mini wasmachine',
    'Mobiele airco’s',
    'Mobiele pinautomaat',
    'Moestuinbak',
    'Nettoyant pour lave-linge',
    'Nettoyeur de tapis',
    'Office',
    'Opvang- en bewaarbakjes of -zakjes',
    'Ordinateurs: boîtiers, access.',
    'Paille de fer',
    'Pailles à boire',
    'Panty',
    'Parasol',
    'partie scooter',
    'Peigne',
    'Piscine : outils de nettoyage',
    'Plafondlamp met ventilator',
    'Plomberie et équipements sanitaires',
    'Poignées de vélo',
    'Pompe pour filtre de piscine',
    'Pool Equipment & Parts',
    'Pressure Washer Parts & Accessories',
    'Produit d\'entretien pour véhicules',
    'Produit vaisselle',
    'Purificateur d \'air',
    'Purificazione dell\'acqua',
    'Regencover',
    'Routeur Mifi',
    'Réfrigérateurs avec congélateur en bas',
    'Réfrigérateurs encastrables',
    'Réhausseur',
    'Réservoir sous vide',
    'Schrobborstel',
    'Scies électriques',
    'Serpillières, pièces et accessoires',
    'Slabbetje',
    'Speaker Parts & Components',
    'Speelhuisje voor dieren',
    'Strumenti di misurazione e layout',
    'Suikervervanger',
    'Surfing',
    'Tapijtreiniger',
    'Tapis de voiture',
    'Taques induction',
    'Tige de guidon',
    'Toetsenbordcover',
    'Tondeuse à gazon',
    'Télécommande ou extension infrarouge',
    'Ventilateur de salle de bains',
    'Voetenbankje',
    'Vrijstaande microgolfovens met grill',
    'Wasmachine-onderhoud',
    'Zwembad afdekzeil',
    'Éplucheur',
];
